<?php

// TODO - sort out page titles so they only show the filename
// TODO - sort out toggle menu for sub-ul's

include 'docDisplay/config.php'; // Include configuration settings
require_once 'docDisplay/php-markdown-lib/Michelf/Markdown.php'; // Include Markdown parser

$homePageURL = "./index.php?file=".$homePage;



// Functions to setup the menu list



function menuSetup($i)
// Based on http://stackoverflow.com/questions/10779546/recursiveiteratoriterator-and-recursivedirectoryiterator-to-nested-html-lists
{
    global $homePageURL;
    $depth = 0;
    $logo = '<li class="sidebar-brand nav nav-list"><a href="'.$homePageURL.'"><img src="../website_code/images/xerteLogo.jpg" alt="Xerte logo" /></a></li>';
    $menu = $menu.'<ul class="sidebar-nav">';
    $menu = $menu.$logo;

    foreach ($i as $path) {
        $depth1 = $i->getDepth();
        $pathName = $i->getPathname();
        
        if ($depth < $depth1)
        {
            $menu = $menu.'<ul>';
            $depth = $depth1;
        }
        elseif ($depth > $depth1) {
            $menu = $menu. '</ul>';
            $depth = $depth1;
        }
        
           $menu = $menu.'<li><a href="index.php?file='.$pathName.'">'.createPageName($fileName).'</a></li>';
            $previousItem = $i;
    }
    $menu = $menu.'</ul>';
    return $menu;
}

// Setup iterator for previous function
$dir = $docsDir;
$iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir),RecursiveIteratorIterator::SELF_FIRST );

// End of menusetup



function createPageName($fname) {

    $name = str_replace(".md", "", $fname); // remove extension
    $name = str_replace("-", " ", $name); // replace - with space
    $name = str_replace("_", " ", $name); // replace - with space
    $name = ucwords($name); // set first character to be a capital letter

// Remove numbers from name if they exist
    if (is_numeric(substr($name, 0,1))) {
        $name = substr($name, 2, strlen($name)-2);
    }

    return $name;

}


// Get markdown file to display from URL

$URLfileName = $_GET['file']; // Pick up the filename from the URL

if (is_null($URLfileName)) { // If no filename - go to the home page
    $URLfileName = $homePage;
}




// Get the names ready to display on the page

$URLpageName = createPageName($URLfileName);

// Put contents of file into string

$fileContents = file_get_contents($URLfileName);

// Translate from markdown to HTML

$fileHtml = \Michelf\Markdown::defaultTransform($fileContents);

// Create page title
$pageTitle = $application.' Documentation > '.$URLcategory.' > '.$URLpageName;

?>

<!DOCTYPE html>
<html>
<head>
    <title><?php echo $pageTitle ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap-theme.min.css">


<!-- Bootstrap core JavaScript
    ================================================== -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>

<!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
    

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <link href="docDisplay/css/simple-sidebar.css" rel="stylesheet">
</head>

<body>
    <script>
 
    var docsName = "<?php echo $docsDir; ?>";


    $( document ).ready(function() {
// Function to replace URLs in the page content generated by the markdown with ones that will work locally
        $('#page-content-wrapper a').each(function() {
        $(this).attr("href", function(index, old) {
            
            newstring1 = old.replace(docsName, "index.php?file="); // Add the index.php piece
            newstring2 = newstring1.replace(/=\/(.+?)/,'=$1'); // Find the string after the = and replace the \

            
            if (newstring2 != newstring1) { // only deal with URL's that had the index.php added
                newstring2 = newstring2 + '.md'; // add .md to the end of the URL
                }

            newstring3 = newstring2.replace(/\/.md/,'.md'); // Deal with any URLs with a stray /

            return newstring3;

            
        });
        });

        
    });
 
    </script>
    <!--<div class="container theme-showcase">-->
    <div id="wrapper">
    <!-- Sidebar -->
        <div id="sidebar-wrapper">

            <?php
          // print list of files in docsDir as menu
            echo menuSetup($iterator);  
            ?>  
        
        </div>

      <!-- Main space for a primary marketing message or call to action -->
      <div class="well">
        <h1><?php echo $application; ?> > Documentation</h1>
        <p><?php echo $intro; ?></p>
      </div>
      
      
          
      <!-- Page content -->
      <div id="page-content-wrapper">
        <div class="content-header">
          <h1>
            <a id="menu-toggle" href="#" class="btn btn-default"><i class="icon-reorder"></i></a>
            <?php
                // echo $URLcategory.' / '.$URLpageName;
                echo $URLpageName;
                ?>
          </h1>
        </div>
        <!-- Keep all page content within the page-content inset div! -->
        <div class="page-content inset">
            <?php
                echo $fileHtml; // print out markdown file contents
                ?>

        </div>
      </div>
      
    
        
    

    





      



</div> <!-- Wrapper-->


    

    <!-- Custom JavaScript for the Menu Toggle -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("active");
    });
    </script>

  </body>


</html>